import { NextResponse } from "next/server";
import { initDB, sql } from "@/lib/db";
import { hashPassword } from "@/lib/auth";

const demoUsers = [
  { email: "tunde@finsupport.com", password: "admin123", name: "Tunde Olaniyan", role: "super_admin", team: "AI Operations" },
  { email: "chioma@finsupport.com", password: "demo123", name: "Chioma Nwankwo", role: "admin", team: "Compliance" },
  { email: "adebayo@finsupport.com", password: "demo123", name: "Adebayo Martins", role: "manager", team: "Fraud Detection" },
  { email: "folake@finsupport.com", password: "demo123", name: "Folake Balogun", role: "manager", team: "Customer Success" },
  { email: "emeka@finsupport.com", password: "demo123", name: "Emeka Chukwu", role: "agent", team: "AI Operations" },
  { email: "ngozi@finsupport.com", password: "demo123", name: "Ngozi Okafor", role: "agent", team: "Compliance" },
  { email: "adaeze@finsupport.com", password: "demo123", name: "Adaeze Uche", role: "agent", team: "Fraud Detection" },
  { email: "bola@finsupport.com", password: "demo123", name: "Bola Fashola", role: "agent", team: "Customer Success" },
  { email: "kemi@finsupport.com", password: "demo123", name: "Kemi Akinwale", role: "agent", team: "AI Operations" },
  { email: "dayo@finsupport.com", password: "demo123", name: "Dayo Coker", role: "viewer", team: null },
];

const demoCustomers = [
  { email: "support@paystack.com", name: "Paystack Support", company: "Paystack", segment: "enterprise", plan: "enterprise", ltv: 72000000, csat: 4.8, total_tickets: 25 },
  { email: "help@flutterwave.com", name: "Flutterwave Help", company: "Flutterwave", segment: "enterprise", plan: "enterprise", ltv: 65000000, csat: 4.7, total_tickets: 22 },
  { email: "ops@kuda.com", name: "Kuda Operations", company: "Kuda Bank", segment: "business", plan: "business", ltv: 34500000, csat: 4.5, total_tickets: 15 },
  { email: "support@carbon.com", name: "Carbon Support", company: "Carbon", segment: "pro", plan: "pro", ltv: 21000000, csat: 4.6, total_tickets: 11 },
  { email: "team@moniepoint.com", name: "Moniepoint Team", company: "Moniepoint", segment: "enterprise", plan: "enterprise", ltv: 58000000, csat: 4.9, total_tickets: 30 },
  { email: "help@opay.com", name: "OPay Help", company: "OPay", segment: "business", plan: "business", ltv: 41000000, csat: 4.4, total_tickets: 18 },
  { email: "support@palm-pay.com", name: "PalmPay Support", company: "PalmPay", segment: "pro", plan: "pro", ltv: 18000000, csat: 4.3, total_tickets: 8 },
  { email: "ops@vbank.com", name: "VBank Ops", company: "VBank", segment: "starter", plan: "starter", ltv: 5400000, csat: 4.2, total_tickets: 4 },
  { email: "team@sparkle.com", name: "Sparkle Team", company: "Sparkle", segment: "business", plan: "business", ltv: 28000000, csat: 4.7, total_tickets: 12 },
  { email: "support@fairmoney.com", name: "FairMoney Support", company: "FairMoney", segment: "starter", plan: "starter", ltv: 4800000, csat: 4.5, total_tickets: 6 },
];

const demoKnowledgeArticles = [
  { title: "How to Process a Refund", content: "To process a refund, navigate to the Transactions module and locate the original transaction by reference ID or customer details. Click 'Initiate Refund' and select full or partial refund amount, then confirm the action. Refunds are processed within 24-48 hours and reflected in the customer's wallet or bank account depending on the original payment method.", collection: "Payments & Transactions", status: "published", views: 3421, ai_used: 234, helpful: 92, tags: ["refund", "transactions", "payments"] },
  { title: "Understanding Transaction Limits", content: "FinSupport enforces daily and monthly transaction limits based on customer KYC tier and account type. Tier 1 accounts have a ₦50,000 daily limit, Tier 2 accounts ₦500,000, and Tier 3 accounts up to ₦5,000,000. Monthly limits are calculated as 30x the daily limit. Customers can view their current limits in the app under Account > Transaction Limits.", collection: "Payments & Transactions", status: "published", views: 2876, ai_used: 198, helpful: 89, tags: ["limits", "transactions", "tiers"] },
  { title: "KYC Tier Verification Levels", content: "FinSupport follows CBN KYC guidelines with three verification tiers. Tier 1 requires basic information (name, phone, DOB) for basic transactions. Tier 2 adds BVN verification for higher limits. Tier 3 requires NIN, government-issued ID, and proof of address for full access. Verification is processed through our NIBSS integration and typically completes within 24 hours.", collection: "Compliance & KYC", status: "published", views: 4521, ai_used: 312, helpful: 95, tags: ["kyc", "verification", "bvn", "nin"] },
  { title: "Setting Up Webhook Notifications", content: "Configure webhooks in Settings > API > Webhooks to receive real-time alerts for payment events. Available events include payment.success, payment.failed, transfer.completed, and chargeback.received. Each webhook includes an HMAC signature for verification. Set up a retry policy with exponential backoff for failed deliveries and monitor delivery status in the webhook logs.", collection: "Integrations", status: "published", views: 1987, ai_used: 143, helpful: 93, tags: ["webhook", "api", "notifications"] },
  { title: "Resolving Failed Transactions", content: "Failed transactions in FinSupport typically occur due to insufficient funds, network timeouts, incorrect account details, or bank gateway downtime. Check the transaction status code in the audit log to identify the specific failure reason. For network timeouts, the system automatically retries up to 3 times before marking as failed. Customers should verify account details and retry, or contact their bank if the issue persists.", collection: "Troubleshooting", status: "published", views: 3210, ai_used: 245, helpful: 87, tags: ["failed", "transactions", "errors", "troubleshooting"] },
  { title: "Configuring Split Payment Rules", content: "Split payment rules allow automatic distribution of received payments across multiple accounts. Navigate to Settings > Payment Rules > Split Payments to configure. Define percentage-based or fixed-amount splits per recipient. Rules can be triggered by payment source, amount threshold, or merchant category. All splits are reconciled in real-time and appear in the settlement report.", collection: "Payments & Transactions", status: "published", views: 1654, ai_used: 121, helpful: 88, tags: ["split", "payments", "rules", "configuration"] },
  { title: "Understanding Chargeback Processing", content: "Chargebacks occur when a customer disputes a transaction through their bank. FinSupport receives the dispute notification and provides a 7-day window to respond with evidence. Upload transaction records, delivery confirmations, or customer communications to the dispute portal. If evidence is insufficient, the chargeback is accepted and funds debited from the merchant account. Track all chargebacks in the Disputes dashboard.", collection: "Payments & Transactions", status: "published", views: 2109, ai_used: 167, helpful: 91, tags: ["chargeback", "disputes", "transactions"] },
  { title: "How to Integrate with NIBSS", content: "FinSupport connects to NIBSS (Nigeria Inter-Bank Settlement System) for NIP transfers and account validation. Integration requires a valid NIBSS license and API credentials configured in Settings > Integrations > NIBSS. The API supports name enquiry, balance inquiry, and NIP transfers. All NIBSS transactions are encrypted end-to-end and comply with CBN security standards.", collection: "Integrations", status: "published", views: 2345, ai_used: 178, helpful: 90, tags: ["nibss", "nip", "integration", "banking"] },
  { title: "Setting Up USSD Payment Channels", content: "Enable USSD payments by navigating to Settings > Channels > USSD. Configure your USSD short code with your mobile network operator. Set up menu options for balance inquiry, transfers, and bill payments. USSD sessions timeout after 180 seconds. Ensure your USSD gateway handles session state correctly to prevent transaction failures. Test the flow with sample transactions before going live.", collection: "Payments & Transactions", status: "published", views: 1234, ai_used: 89, helpful: 86, tags: ["ussd", "payments", "mobile"] },
  { title: "Card Transaction Dispute Resolution", content: "Card disputes are initiated through the card scheme (Verve, Mastercard, Visa) and routed to FinSupport's dispute module. Upload supporting documentation including transaction receipts, customer consent records, and delivery proof within 45 days. The dispute team reviews evidence and responds to the issuing bank. Resolution typically takes 30-45 days. Track dispute status and outcomes in the Disputes analytics dashboard.", collection: "Payments & Transactions", status: "published", views: 1543, ai_used: 112, helpful: 85, tags: ["card", "disputes", "verve", "mastercard"] },
  { title: "Understanding CBN Regulatory Requirements", content: "FinSupport complies with all Central Bank of Nigeria (CBN) regulations for financial technology companies. Key requirements include maintaining minimum capital adequacy ratios, reporting suspicious transactions within 24 hours, implementing robust AML/CFT controls, and submitting quarterly returns. Non-compliance can result in penalties or license revocation. Review the full compliance checklist in Settings > Compliance > CBN Requirements.", collection: "Compliance & KYC", status: "published", views: 1876, ai_used: 134, helpful: 90, tags: ["cbn", "regulations", "compliance"] },
  { title: "Configuring Fraud Detection Rules", content: "Set up fraud detection rules in Settings > Security > Fraud Rules. Define thresholds for transaction velocity, amount limits, geographic anomalies, and device fingerprinting. Rules can trigger actions such as blocking transactions, requiring additional verification, or flagging accounts for review. The ML-based fraud engine learns from historical data and adapts to new patterns. Review flagged transactions daily in the Fraud Dashboard.", collection: "Fraud Detection", status: "published", views: 2876, ai_used: 198, helpful: 91, tags: ["fraud", "security", "rules", "detection"] },
  { title: "Setting Up Bulk Payment Processing", content: "Enable bulk payments in Settings > Payments > Bulk Processing. Upload a CSV file with recipient details (account number, bank code, amount, narration). The system validates all entries before processing. Bulk payments are queued and processed in batches every 15 minutes. Monitor progress in the Bulk Payments dashboard. Failed payments are automatically flagged for review with detailed error codes.", collection: "Payments & Transactions", status: "published", views: 1654, ai_used: 121, helpful: 88, tags: ["bulk", "payments", "payroll"] },
  { title: "How to Reconcile Transactions", content: "Reconciliation in FinSupport matches internal transaction records with bank statements. Navigate to Finance > Reconciliation and select the date range. The system automatically matches 95% of transactions. Manual matching is available for discrepancies. Unmatched transactions are flagged with reasons (timing differences, amount mismatches, missing records). Generate reconciliation reports for audit purposes.", collection: "Payments & Transactions", status: "published", views: 2345, ai_used: 178, helpful: 90, tags: ["reconciliation", "finance", "banking"] },
  { title: "Managing Merchant Accounts", content: "Merchant accounts are managed through Settings > Merchants. Create new merchant profiles with business details, bank account information, and settlement preferences. Configure merchant-specific transaction fees, limits, and payout schedules. Each merchant receives unique API keys and webhook endpoints. Monitor merchant activity, transaction volumes, and settlement status in the Merchant Dashboard.", collection: "Account Management", status: "published", views: 1987, ai_used: 143, helpful: 89, tags: ["merchant", "accounts", "management"] },
  { title: "WhatsApp for Transaction Alerts", content: "Configure WhatsApp transaction alerts via Settings > Channels > WhatsApp Business API. Map transaction events (credit, debit, failed) to WhatsApp templates. Templates must be approved by Meta before use. Alerts include transaction amount, reference ID, and timestamp. WhatsApp delivery provides higher open rates (98%) compared to SMS (20%). Monitor delivery status and template performance in the Analytics dashboard.", collection: "Integrations", status: "published", views: 1234, ai_used: 89, helpful: 86, tags: ["whatsapp", "alerts", "notifications"] },
  { title: "Email Integration for Support", content: "Set up email integration in Settings > Channels > Email. Configure IMAP settings for receiving support emails and SMTP for sending responses. FinSupport supports Gmail, Outlook, and custom mail servers. Enable auto-classification to automatically route emails to the appropriate department. Configure email templates for consistent branding across all responses.", collection: "Integrations", status: "published", views: 987, ai_used: 76, helpful: 84, tags: ["email", "imap", "smtp", "support"] },
  { title: "Building a Financial Knowledge Base", content: "Create a comprehensive knowledge base in Settings > Knowledge Base. Organize articles by category (Payments, Account, Compliance, Technical). Use the rich text editor for formatting, add code snippets for API docs, and include screenshots for workflows. Enable AI-powered search to help agents find relevant articles quickly. Track article performance with views, helpful votes, and AI usage metrics.", collection: "Getting Started", status: "published", views: 4521, ai_used: 312, helpful: 95, tags: ["knowledge-base", "documentation", "articles"] },
  { title: "Understanding AI Fraud Scoring", content: "FinSupport's AI fraud scoring engine analyzes every transaction in real-time using machine learning models trained on millions of transactions. The score ranges from 0-100, with scores above 70 flagged as high-risk. Factors include transaction amount, frequency, location, device fingerprint, and historical patterns. False positives are minimized through continuous model training. Review flagged transactions in the Fraud Dashboard and adjust thresholds as needed.", collection: "Fraud Detection", status: "published", views: 3421, ai_used: 234, helpful: 92, tags: ["ai", "fraud", "scoring", "machine-learning"] },
  { title: "Setting Up Virtual Card Management", content: "Enable virtual card issuance in Settings > Cards > Virtual Cards. Configure card limits, merchant category restrictions, and expiry dates. Virtual cards can be created instantly for online transactions and subscriptions. Each card has a unique PAN, CVV, and expiry date. Freeze or unfreeze cards in real-time. Monitor card spending and transaction history in the Cards dashboard.", collection: "Payments & Transactions", status: "published", views: 1876, ai_used: 134, helpful: 90, tags: ["virtual-cards", "cards", "payments"] },
  { title: "Treasury and Liquidity Management", content: "Manage treasury operations in Finance > Treasury. Monitor real-time balances across all bank accounts, optimize liquidity positions, and forecast cash flow. Set up automated sweeps between accounts to maintain optimal balances. Generate daily treasury reports showing inflows, outflows, and net positions. Configure alerts for low balance thresholds and unusual flow patterns.", collection: "Payments & Transactions", status: "published", views: 1654, ai_used: 121, helpful: 88, tags: ["treasury", "liquidity", "cash-flow"] },
  { title: "Multi-Currency Transaction Support", content: "FinSupport supports multi-currency transactions for international payments. Configure supported currencies in Settings > Payments > Currencies. Exchange rates are updated in real-time from CBN and parallel market sources. Transactions are automatically converted at the prevailing rate. FX charges are transparently displayed before confirmation. Generate FX exposure reports for risk management.", collection: "Payments & Transactions", status: "published", views: 1234, ai_used: 89, helpful: 86, tags: ["multi-currency", "forex", "international"] },
  { title: "Real-Time Balance Inquiries", content: "Customers can check their wallet balance in real-time through the mobile app, USSD, or API. Balance inquiries are processed instantly via the NIBSS BVN validation API. API endpoints return cached balances with a 30-second TTL for performance. For regulatory compliance, balance inquiries are logged and included in transaction reports. Configure balance notification thresholds to alert customers of low funds.", collection: "Payments & Transactions", status: "published", views: 987, ai_used: 76, helpful: 84, tags: ["balance", "inquiries", "real-time"] },
  { title: "Dispute Resolution Workflow", content: "The dispute resolution workflow in FinSupport follows a structured process: intake (customer complaint), investigation (evidence gathering), resolution (decision), and enforcement (fund reversal or rejection). SLAs are set at 7 days for investigation and 3 days for resolution. All communications are logged in the dispute timeline. Escalation rules automatically route complex disputes to senior analysts.", collection: "Payments & Transactions", status: "published", views: 1432, ai_used: 109, helpful: 87, tags: ["disputes", "resolution", "workflow"] },
  { title: "Configuring Payment Gateway Rules", content: "Payment gateway rules determine how transactions are routed and processed. Configure in Settings > Payments > Gateway Rules. Set rules by payment method (card, bank transfer, USSD), transaction amount, and merchant category. Define fallback gateways for failover. Enable 3D Secure for high-value transactions. Monitor gateway performance and success rates in the Analytics dashboard.", collection: "Payments & Transactions", status: "published", views: 2109, ai_used: 167, helpful: 91, tags: ["gateway", "payments", "routing", "configuration"] },
  { title: "Understanding Settlement Cycles", content: "FinSupport offers flexible settlement cycles: T+0 (same-day), T+1 (next business day), and T+2 (two business days). Configure settlement preferences per merchant in Settings > Merchants > Settlement. Settlements are processed automatically at the configured cutoff time. Generate settlement reports showing gross amounts, fees, chargebacks, and net payouts. Track settlement status in real-time in the Finance dashboard.", collection: "Payments & Transactions", status: "published", views: 1876, ai_used: 134, helpful: 90, tags: ["settlement", "payouts", "finance"] },
  { title: "Setting Up BVN Validation", content: "BVN validation is required for KYC compliance and account verification. Configure in Settings > Compliance > BVN Validation. The API validates BVN against NIBSS records and returns the customer's name, date of birth, phone number, and photo. Validation is synchronous and returns results within 2 seconds. Failed validations are logged for review. BVN validation is mandatory for Tier 2 and Tier 3 accounts.", collection: "Compliance & KYC", status: "published", views: 2345, ai_used: 178, helpful: 90, tags: ["bvn", "validation", "kyc", "compliance"] },
  { title: "Data Privacy and NDPR Compliance", content: "FinSupport complies with Nigeria Data Protection Regulation (NDPR) requirements. Customer data is encrypted at rest and in transit using AES-256. Data access is logged and auditable. Customers can request data export or deletion through the app. Data retention policies are configured in Settings > Privacy. Appoint a Data Protection Officer (DPO) and conduct annual data protection impact assessments.", collection: "Compliance & KYC", status: "published", views: 1543, ai_used: 112, helpful: 85, tags: ["ndpr", "privacy", "data-protection", "compliance"] },
  { title: "Troubleshooting API Webhook Failures", content: "Webhook failures can occur due to network timeouts, invalid endpoints, SSL certificate issues, or server errors. Check webhook delivery logs in Settings > API > Webhook Logs for detailed error codes. Verify your endpoint is accessible and returns a 2xx status code within 30 seconds. Enable retry logic for transient failures. Use the webhook testing tool to validate your endpoint before activating.", collection: "Troubleshooting", status: "published", views: 1234, ai_used: 89, helpful: 86, tags: ["webhook", "api", "troubleshooting", "errors"] },
  { title: "Mobile Banking App Integration", content: "Integrate FinSupport's SDK into your mobile banking app for embedded support. The SDK supports iOS (Swift) and Android (Kotlin) with native UI components. Configure the widget appearance, language, and routing rules in the FinSupport dashboard. The SDK includes features for in-app chat, ticket submission, knowledge base search, and push notifications. Track SDK usage and performance in the Mobile Analytics dashboard.", collection: "Integrations", status: "published", views: 1876, ai_used: 134, helpful: 90, tags: ["mobile", "sdk", "integration", "app"] },
];

const demoTickets = [
  { subject: "Transaction failed but account debited", message: "A customer transferred ₦150,000 to another bank via NIP but the transaction failed with error code 91. The customer's account was debited but the recipient didn't receive the funds. We need to reverse the transaction immediately.", status: "open", priority: "high", channel: "whatsapp", sentiment: "angry", sentiment_score: -0.7, ai_confidence: 94, tags: ["transaction", "failed", "reversal", "urgent"] },
  { subject: "How to process bulk salary payments", message: "We need to process salary payments for 500 employees this Friday. What is the recommended approach for bulk payments? We need to ensure all payments settle on the same day.", status: "open", priority: "medium", channel: "email", sentiment: "neutral", sentiment_score: 0.1, ai_confidence: 88, tags: ["bulk", "payments", "payroll", "how-to"] },
  { subject: "Customer KYC verification stuck at BVN", message: "A customer has been trying to complete KYC verification for 3 days. The BVN validation keeps returning 'BVN not found' even though the BVN is correct. The customer needs Tier 3 access for international transfers.", status: "escalated", priority: "high", channel: "web", sentiment: "frustrated", sentiment_score: -0.5, ai_confidence: 72, tags: ["kyc", "bvn", "verification", "stuck"] },
  { subject: "Need to set up webhook for payment alerts", message: "We want to receive real-time notifications when payments are completed or failed. How do we configure webhooks for our payment processing system? We're using the REST API.", status: "open", priority: "low", channel: "messenger", sentiment: "neutral", sentiment_score: 0.2, ai_confidence: 96, tags: ["webhook", "integration", "api", "setup"] },
  { subject: "Chargeback received from customer", message: "We received a chargeback notification for transaction REF-2024-78456 for ₦85,000. The customer claims they didn't authorize the transaction. We have the OTP confirmation and IP address logs. How do we respond within the deadline?", status: "pending", priority: "high", channel: "email", sentiment: "worried", sentiment_score: -0.4, ai_confidence: 85, tags: ["chargeback", "dispute", "urgent", "compliance"] },
  { subject: "Daily transaction limit exceeded", message: "A merchant customer needs to process ₦8,000,000 in transactions today but has hit the daily limit of ₦5,000,000. They're on Tier 3 and this is a legitimate business transaction. Can we temporarily increase the limit?", status: "open", priority: "medium", channel: "sms", sentiment: "neutral", sentiment_score: 0.0, ai_confidence: 91, tags: ["limits", "merchant", "escalation"] },
  { subject: "How to enable multi-factor authentication", message: "We need to enable MFA for all admin accounts in our organization. What options are supported? We prefer authenticator apps over SMS for security reasons.", status: "open", priority: "low", channel: "web", sentiment: "positive", sentiment_score: 0.3, ai_confidence: 97, tags: ["security", "mfa", "authentication", "how-to"] },
  { subject: "Reconciliation discrepancy in today's report", message: "Our daily reconciliation report shows a ₦2,300,000 discrepancy between internal records and bank statements. This started after the NIBSS maintenance last night. We need help identifying the mismatched transactions.", status: "escalated", priority: "urgent", channel: "email", sentiment: "angry", sentiment_score: -0.6, ai_confidence: 68, tags: ["reconciliation", "discrepancy", "critical", "finance"] },
  { subject: "Virtual card declined on international sites", message: "Several customers are reporting that their virtual cards are being declined on international merchant websites (Netflix, Spotify, Amazon). The cards work fine on Nigerian sites. Is this a configuration issue?", status: "open", priority: "medium", channel: "whatsapp", sentiment: "frustrated", sentiment_score: -0.3, ai_confidence: 88, tags: ["virtual-card", "international", "declined"] },
  { subject: "API rate limit being exceeded during peak hours", message: "Our API calls are being throttled during peak hours (12pm-2pm and 6pm-9pm) when transaction volume is highest. We're on the enterprise plan with 1000 req/min limit. Can we get an increase or priority queue?", status: "open", priority: "medium", channel: "web", sentiment: "negative", sentiment_score: -0.2, ai_confidence: 92, tags: ["api", "rate-limit", "enterprise", "performance"] },
];

export async function POST() {
  try {
    await initDB();

    for (const user of demoUsers) {
      const hash = await hashPassword(user.password);
      await sql`
        INSERT INTO users (email, password_hash, name, role, team)
        VALUES (${user.email}, ${hash}, ${user.name}, ${user.role}, ${user.team})
        ON CONFLICT (email) DO NOTHING
      `;
    }

    const customerIds: string[] = [];
    for (const c of demoCustomers) {
      const result = await sql`
        INSERT INTO customers (email, name, company, segment, plan, ltv, csat, total_tickets)
        VALUES (${c.email}, ${c.name}, ${c.company}, ${c.segment}, ${c.plan}, ${c.ltv}, ${c.csat}, ${c.total_tickets})
        ON CONFLICT (email) DO UPDATE SET name = ${c.name}
        RETURNING id
      `;
      customerIds.push(result[0].id);
    }

    const users = await sql`SELECT id, email FROM users`;
    const userIdMap: Record<string, string> = {};
    for (const u of users) userIdMap[u.email] = u.id;

    for (let i = 0; i < demoTickets.length; i++) {
      const t = demoTickets[i];
      const customerId = customerIds[i % customerIds.length];
      const assigneeId = userIdMap["emeka@finsupport.com"];
      const ticketNumber = `FIN-${1234 - i}`;
      const slaDue = new Date(Date.now() + (t.priority === "urgent" ? 3600000 : t.priority === "high" ? 7200000 : 14400000));

      await sql`
        INSERT INTO tickets (ticket_number, subject, message, status, priority, channel, customer_id, assignee_id, sentiment, sentiment_score, ai_confidence, sla_status, sla_due, tags)
        VALUES (${ticketNumber}, ${t.subject}, ${t.message}, ${t.status}, ${t.priority}, ${t.channel}, ${customerId}, ${assigneeId}, ${t.sentiment}, ${t.sentiment_score}, ${t.ai_confidence}, 'ok', ${slaDue.toISOString()}, ${t.tags})
        ON CONFLICT (ticket_number) DO NOTHING
      `;
    }

    const adminUserId = userIdMap["tunde@finsupport.com"];
    await sql`DELETE FROM knowledge_articles`;
    for (const article of demoKnowledgeArticles) {
      await sql`
        INSERT INTO knowledge_articles (title, content, collection, status, views, ai_used, helpful, tags, created_by)
        VALUES (${article.title}, ${article.content}, ${article.collection}, ${article.status}, ${article.views}, ${article.ai_used}, ${article.helpful}, ${article.tags}, ${adminUserId})
      `;
    }

    return NextResponse.json({
      message: "Database seeded successfully",
      logins: {
        admin: "tunde@finsupport.com / admin123",
        manager: "folake@finsupport.com / demo123",
        agent: "emeka@finsupport.com / demo123",
        viewer: "dayo@finsupport.com / demo123",
      },
    });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json({ error: "Failed to seed database" }, { status: 500 });
  }
}
